### ISSUE TITLE
പരിവർത്തനം Not working

### ISSUE THREAD

**Issue by ByteJoseph** [makersofkerala/thengascript#16]
// its showing error
പരിവർത്തനം k = 2;
കാണിക്കുക(k);

**Comment by ByteJoseph** [comment]
Error:  SyntaxError: Unexpected identifier

**Comment by prathyvsh** [comment]
This is a unicode encoding issue. The keyword used here `പരിവർത്തനം` is not the same as `പരിവര്‍ത്തനം`. That might sound funny, but try doing a .length on each of these. The second one uses a non-width joiner instead of the ചില്ലക്ക്ഷരം `ർ`.

Please use the one with non-width joiner: `പരിവര്‍ത്തനം` and it should get it working.

Will think if I should add a redundant keyword here. Thanks for the note.

**Comment by madhaven** [comment]
ready to close?
@prathyvsh
